### ISSUE TITLE
Count duplicates and delete them when icon is clicked

### ISSUE THREAD

**Issue by allanwind** [igorlogius/close-all-duplicate-tabs#1]
**Is your feature request related to a problem? Please describe.**

I like the minimal nature of the add-on but the "show remove notification" isn't optimal either set or unset.  If set you get interrupted with a pop-up that you have to dismiss.  If unset you have pay close attention notice that one of your tabs was just closed. Both demand your attention now but the only cost of delaying action is extra memory usage.

**Describe the solution you'd like**

Would it be possible for the add-on to simply count number of duplicates, show if >0 (instead of on), and when you click the icon it would delete all the duplicates like now?

**Describe alternatives you've considered**

Duplicate Tab Close works similar but I suspect is has a bug that cause all UI dialogs to be auto-closed right away.  In either case, it is kinda bloated, and you have to click on the icon, wait for it show the tabs, and only then can you close it.  FoxyTab, TabSearch, Tab Deduber all lack the visual indication of duplicate tabs.

**Additional context**

**Comment by igorlogius** [comment]
I think ... this is the closes i'll be able to get to what you want. 


https://user-images.githubusercontent.com/67047467/225942536-f6caa50a-ce58-423f-8d3e-ce5e49595edc.mp4

FYI: in the video the first "New Tab" has a different internal URL from the New Tabs i create aftwards via `CTRL+t` or the `+` button in the tabstrip. That is why it is not counted or closed.

**Comment by allanwind** [comment]
Looks awesome!  Two super minor comments: 1. There is momentary blip at 0:24 which I think is when the page transitions from a blank page to a url you wanted to see.  I wonder if there is a way to suppress that first event so we only see the duplicate.  It's unlikely that I will have a blank page hanging but it's so close to perfect.  2. Please only show badge when the count is 0.  It catches your eye better when it goes from nothing to the badge.  Good choice of badge color.  In either case I would be happy use it as is.

**Comment by igorlogius** [comment]
https://user-images.githubusercontent.com/67047467/225988346-333593dd-4b11-440f-9a2e-25c879a29468.mp4

**Comment by allanwind** [comment]
Perfect!

**Comment by allanwind** [comment]
Where do I find it on addons.mozilla.org?  The earlier link no longer works and I tried https://addons.mozilla.org/en-US/firefox/addon/close-all-duplicate-tabs/ in line with the renamed repo.

**Comment by igorlogius** [comment]
Review on AMO is pending.

**Comment by allanwind** [comment]
Thank you again.

**Comment by igorlogius** [comment]
I'll post the link here, when the review is done.

**Comment by igorlogius** [comment]
@allanwind 

https://addons.mozilla.org/en-US/firefox/addon/close-all-duplicate-tabs/

**Comment by allanwind** [comment]
Left you a 5 star review on AOM. Let me know if you want me to say anything else.  The description says "leaving the last accesed ones 
open".  It leaves the oldest one, as far as I can tell, and that's correct behavior.  I am still seeing the momentary count of 1 when opening new tabs but I think there is a fix under way for that.

**Comment by igorlogius** [comment]
> Left you a 5 star review on AOM for the addon. 

Thanks.

>  The description says "leaving the last accesed ones open". 

ah, ... thanks. Have to fix that some time in the future. 

> I am still seeing the momentary count of 1 when opening new tabs 

I dont see that on my side. Can you share a screencap showing it?

**Comment by allanwind** [comment]
https://user-images.githubusercontent.com/430025/226155222-5b51768c-3faf-4dd0-bd38-976ed8cf0fec.mp4

**Comment by igorlogius** [comment]
I think i know what the issue is ... newly created tabs are created async. and initally get the `about:newtab` url ... before they switch to their real urls. 

The time the newly created tabs get assigned their  real urls ... is dependend on how fast your pc and connection is. - That means that delays of any kind can not really help here. 

So the addon correctly detects  duplicates of  the `about:newtab` , the same  as when you click the `+` button or use `CTRL+t` and the change is the time it takes the tabs to load their real urls.  

At the moment i have no idea how i could reliably distiniguish these. 

I simply way might be to just completely ignore the `about:newtab` urls, if that is something you could live with.

**Comment by igorlogius** [comment]
As a minor workaround ... i created 1.0.3 ... it might not be perfect ... but maybe it's a good enough solution.

**Comment by allanwind** [comment]
Looks good to me (1.0.3).   Just thinking aloud here...  didn't you use a settled event earlier?  Maybe that's how you can defer to check till the final url has been loaded without relying on a delay.
