### ISSUE TITLE
Badge count temporarily out of date after delete with a large number of tabs

### ISSUE THREAD

**Issue by allanwind** [igorlogius/close-all-duplicate-tabs#3]
I am almost embarrassed to mentioned this as it's so minor but it feels buggy:

1. With a large number of tabs open (I seriously have >500).
2. Open 50+ more tabs including say 10 duplicates.  It will take a while for those to load at least if it's youtube.com, maybe 60+ seconds.
3. Once the icon shows a duplicate I click on it to delete them and the icon badge immediately clears (awesome!).
4. The badge count will then reset almost right away to old values say, 10, 9, 8, 7... and some point to 0 over the next 60+ seconds. There are two issues with this:

 b1. because the badge count resets always right away you wonder if you actually clicked it or if there was as race condition that meant some duplicates weren't actually deleted
 b2. the counts reflect previous state that is no longer current.

Some ideas:

s1. What if we record the timestamp when the function to count duplicates is initiated, and timestamp when the user clicked on the icon to delete duplicates.  Then ignore any count results that were initiated before the delete?
s2. If we kick off 50 counts, we actually only care about the last one (even if we end up ignoring it).  Is there is a way to cancel the 49 other async count functions?  I haven't noticed a performance problem, btw, so it's more of UX issue of showing old data, and we know after the delete should be 0. 
s3.  After we click the icon simply don't show any badge updates for >200ms.  Long enough that you appreciate that you clicked the icon.  It's at best a work-around for (a).

If this is not clear, let me, and I will record a video for you.

**Comment by igorlogius** [comment]
Before looking into this, i need to have a solid way to reproduce and observe the issue.

**Comment by allanwind** [comment]
It will take a little time but I will get you a way to reproduce it.  Large number of tabs, btw, just means that Firefox is slow.  (As an aside you can open urls from the command line, and with vim you can use gx on a list of urls if you don't know).

**Comment by igorlogius** [comment]
I know and can do all that ... but it's just no fun manually debugging stuff with 500+ tabs open, so i decided to not work on this issue until i have a way to "simulate the issue" in another way or if some alternative means of reproduction can be used, that is less tedious.

i'll be keeping this issue opend and also be marking it with "Help Wanted".

**Comment by allanwind** [comment]
As promised but slightly different version:

1. youtube.com
2. Middle click twice on the first 6 videos (I have `browser.tabs.loadDivertedInBackground | true` not sure if t matters)
3. Wait for the duplicate count > 0 in this case 3 (t=8s)
4. Click the "Close All Duplicate Tabs" icon (t=10s)
5. Wait a little longer and eventually it shows 3 again (for total as 6 as expected)

I didn't capture in this screen counts but sometimes when I click the icon, it behaves as it wasn't clicked or immediately shows the result of a new duplicate count.  This might just be delaying showing any updates for 200ms.

From a UX perspective, when I click the icon, it's ok to delete all duplicates, as such step 5 is a bit surprising as we only deleted whatever duplicates we found at some point in time.  As I mentioned initially, we only really care about result of the last count.  Can we cancel the other, or speed them up by not doing duplicate effort?  Part of the issue is also that it takes 8 seconds to terate though 12 tabs to count 6 duplicates.

https://user-images.githubusercontent.com/430025/235860165-7f058e5e-5732-4942-933c-1a15b569f8d9.mp4

**Comment by igorlogius** [comment]
The addon delays it's badge update until there are no more tabs which are still in a loading state, it just doesnt indicate that it is currently "processing/waiting" for the tabs to settle. 

If you want, i can add a "icon change" that will indicate when the duplicate removal is "working" / "not usable".

**Comment by allanwind** [comment]
There are two issues:

1. When you click on the icon on your video t=21 it goes from 9 to 0 to 4 to 0.  I don't necessarily mind that it changes but it has to settle on no badge long enough that you are sure that you actually clicked it.  click, no badge for 250ms(?), then show current state.  It's a refinement of what we implemented earlier that click on the icon should immediately go to no badge.  The change you made is good but deals with what happens before the click, and point 1 is about what happens right after the click.
2. Let's say we start a count at t_1, t_2, t_3 and at t_click > t_3 we click on the icon.  It so happens we only have the cached result for t_2 (which might be the count as of 10 seconds ago).  What about initiating a new count when at t_click and use that to delete duplicates?  We should ignore the result from t_3 when it comes in as it was initiated before t_click as will have stale data.  Is there a way to *not* delete duplicates created after t_click (i.e. while it's running)?  It's arguably better to delete less than what we wanted than more than what we asked for.

**Comment by igorlogius** [comment]
The "0" is actually an "clock" utf-8 symbol ( ⏰ )
It's the "progessing/working" indicator ... maybe i should use a differnt icon ... since you correctly noted that it looks to similar to a number. 
No duplicates means no badge icon.

Regarding your suggestions ... about the time slot handling ... i have to be honest ... i dont yet get what you mean ... i might have to re-read what you wrote ... when i can concentrate better. 

But in general, i hope you understand that making changes to the process handling ... might involve more work then just tweaking some values, and i am not comfortable rewriting the entire addon as long as it's basic function is working.

**Comment by allanwind** [comment]
Let's try an example:

1. Open a pair of duplicate tabs.  count = 0
2. Wait. count = 1
3. Open a 2nd pair of duplicate tabs.  count = 1 (tab 1)
4. Click delete duplicates. count = **0 (tab 1 is** deleted)
5. Open 3rd pair of duplicate tabs.  count = 0
6. Wait count = **2 (tab 3  and 5)**

What would be better behavior is:

1. Open a pair of duplicate tabs.  count = 0
2. Wait. count = 1
3. Open a 2nd pair of duplicate tabs.  count = 1 tab)
4. Click delete duplicates. count = **0 (tab 1 and 3 are** deleted)
5. Open 3rd pair of duplicate tabs.  count = 0
6. Wait count = **1 (tab 5)**

**Comment by igorlogius** [comment]
Wait ... do you mean you want the counter to groupe the duplicates by url and for each group that has more then at 1 element ... add one point to the counter?


 3 x facebook.com 
 2 x github.com

=> Counter := 2 


Is that what you mean?

**Comment by allanwind** [comment]
No, not at all, the way you count duplicates is perfect.  It's entirely a timing thing.

**Comment by igorlogius** [comment]
Well, i made some changes. Not 100% if they fix this issue, but it should help with some ambiguousness.

**Comment by allanwind** [comment]
I like it.  You disallow delete while the counts are running and the hourglass badge communicates this to the user (at the cost of some responsiveness which I think is a good trade-off).  I would prefer no badge to the green 0.  In our example from earlier this is where we ended up:

1. Open 1s pair of duplicate tabs (url = x). count = **hourglass**
2. Wait. count = 1
3. Open 2nd pair of duplicate tabs (url = y). count = **hourglass**
4. Open 3rd pair of duplicate tabs (url = z). count = **hourglass**
5.  Wait. count = 3 (tab 1, 3, 5)
6. Click delete duplicates. count = 0 (tab 1, 3, 5 are deleted)

**Comment by allanwind** [comment]
We are waiting for the tabs to settle (on Youtube it's many seconds) before we can check if it's a duplicate.  I think this was a work-around for the url going through the blank before ending on the actual url.  If we speed that up it would restore the responsiveness.  Just thinking aloud here...
